# Generated by Django 3.2.19 on 2023-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='name',
            new_name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='In Progess', max_length=30),
        ),
    ]
