# Generated by Django 3.2.19 on 2023-06-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default='student', help_text='student/teacher', max_length=50),
        ),
    ]
