# Generated by Django 3.2.19 on 2023-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineup', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default=None, help_text='student/teacher', max_length=50),
        ),
    ]
