# Generated by Django 3.2.19 on 2023-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineup', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
